spring.application.name=biblo

spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=felipe2002

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update   
epub.cache.dir=F:\epub-cache

application.name=jachcloud
application.security.jwt.secret-key=ccea1cead3c25a065eb36b69a83d5d2dcd770997ac6cdd1c3870f111ff67ed95
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=172800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=soporte@jachperu.pe
spring.mail.password=lhwf drjy wnil ohzw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.http=TRACE
logging.level.your.package=DEBUG